version: '3.8'
services:
  # Banco de Dados MongoDB
  mongo:
    image: mongo:6.0
    container_name: truckpag_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./docker/mongo/data:/data/db

  # Interface Visual (Mongo Express)
  mongo-express:
    image: mongo-express
    container_name: truckpag_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    depends_on:
      - mongo